name: Release Packed Dict

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 5' # 每周五晚上5点执行，根据Github抵消时差后是17-8

jobs:
  packer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "1.12.2"
          - "1.16"
          - "1.16-fabric"
          - "1.18"
          - "1.18-fabric"
          - "1.19"
          - "1.20"
          - "1.20-fabric"
          - "1.21"
    outputs:
      latest: "1.21"
    steps:
      - name: Checkout Scripts
        uses: actions/checkout@main
        with:
          fetch-depth: '1'

      - name: Checkout Language Pack
        uses: actions/checkout@main
        with:
          fetch-depth: '1'
          repository: CFPAOrg/Minecraft-Mod-Language-Package
          path: Minecraft-Mod-Language-Package

      - uses: actions/setup-python@main
        with:
          python-version: "3.10"

      - name: Pack dict
        run: python ./src/packer.py ${{ matrix.version }}

      - name: Upload JSON files
        uses: actions/upload-artifact@main
        with:
          name: Dict-${{ matrix.version }}.json
          path: DictPacker/Dict-${{ matrix.version }}.json
          compression-level: 9

  release:
    needs: packer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Scripts
        uses: actions/checkout@main

      - uses: actions/setup-python@main
        with:
          python-version: "3.10"

      - name: Download JSON files
        uses: actions/download-artifact@main
        with:
          path: DictPacker
          merge-multiple: true

      - name: Pack Integral files
        run: python ./src/integral.py

      - name: Create timestamp
        id: create_timestamp
        run: echo "timestamp=$(date -u '+%Y_%m_%d_%H_%M_%S')" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: 模组词典-${{ steps.create_timestamp.outputs.timestamp }}
          tag_name: 模组词典-${{ steps.create_timestamp.outputs.timestamp }}
          files: |
            Dict.json
            Dict-Mini.json
            Dict-Sqlite.db
          # https://github.com/CFPATools/i18n-dict/actions/runs/${{ github.run_id }}
          body: |
            当前词典的最新版本：${{ needs.packer.outputs.latest }}
            
            你可以在以下 Actions 链接下载各个独立 Minecraft 版本的模组词典：
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
