name: Dict Packer
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - 'projects/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
          ref: main

      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Check changed path on 1.12
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed-1122
        with:
          paths: projects/1.12.2

      - name: Check changed path on 1.16
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed-116
        with:
          paths: projects/1.16
      
      - name: Check changed path on 1.16 fabric
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed-116-fabric
        with:
          paths: projects/1.16-fabric

      - name: Check changed path on 1.18
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed-118
        with:
          paths: projects/1.18

      - name: Check changed path on 1.18 fabric
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed-118-fabric
        with:
          paths: projects/1.18-fabric

      - name: Build Packer
        run: dotnet publish .\src\Packer\Packer.csproj -o ./ -r win-x64 -p:PublishSingleFile=true

      - name: Run Packer
        run: python .\src\Dict\dict-packer.py "1.12.2"
        if: steps.changed-1122.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'

      - name: Run Packer
        run: python .\src\Dict\dict-packer.py "1.16"
        if: steps.changed-116.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'

      - name: Run Packer
        run: python .\src\Dict\dict-packer.py "1.16-fabric"
        if: steps.changed-116-fabric.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'

      - name: Run Packer
        run: python .\src\Dict\dict-packer.py "1.18"
        if: steps.changed-118.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        
      - name: Run Packer
        run: python .\src\Dict\dict-packer.py "1.18-fabric"
        if: steps.changed-118-fabric.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'

      - name: Create timestamp
        id: create_timestamp
        run: echo "::set-output name=timestamp::$(date '+%Y%m%d%H%M%s')"
        shell: bash

      # Create the release: https://github.com/actions/create-release
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Snapshot-${{ steps.create_timestamp.outputs.timestamp }}
          release_name: 模组词典-${{ steps.create_timestamp.outputs.timestamp }}
          draft: false
          prerelease: false

      # Upload release asset: https://github.com/actions/upload-release-asset
      - name: Update release asset
        id: upload-release-asset1
        if: steps.changed-1122.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Dict-1.12.2.json
          asset_name: Dict-1.12.2.json
          asset_content_type: application/json

      - name: Update release asset
        id: upload-release-asset2
        if: steps.changed-116.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Dict-1.16.json
          asset_name: Dict-1.16.json
          asset_content_type: application/json

        
      - name: Update release asset
        id: upload-release-asset3
        if: steps.changed-116-fabric.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Dict-1.16-fabric.json
          asset_name: Dict-1.16-fabric.json
          asset_content_type: application/json

      - name: Update release asset
        id: upload-release-asset4
        if: steps.changed-118.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Dict-1.18.json
          asset_name: Dict-1.18.json
          asset_content_type: application/json

      - name: Update release asset
        id: upload-release-asset5
        if: steps.changed-118-fabric.outputs.changed == 'true' ||  github.event_name == 'workflow_dispatch'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Dict-1.18-fabric.json
          asset_name: Dict-1.18-fabric.json
          asset_content_type: application/json