name: Release Packed Dict

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 5' # 每周五晚上5点执行，根据Github抵消时差后是17-8

jobs:
  packer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "1.12.2"
          - "1.16"
          - "1.16-fabric"
          - "1.18"
          - "1.18-fabric"
          - "1.19"
          - "1.20"
          - "1.20-fabric"
          - "1.21"
    steps:
      - name: Checkout Scripts
        uses: actions/checkout@main
        with:
          fetch-depth: '1'

      - name: Checkout Language Pack
        uses: actions/checkout@main
        with:
          fetch-depth: '1'
          repository: CFPAOrg/Minecraft-Mod-Language-Package
          path: Minecraft-Mod-Language-Package

      - uses: actions/setup-python@main
        with:
          python-version: "3.10"

      - name: Pack dict
        run: python ./src/packer.py ${{ matrix.version }}

      - name: Upload JSON files
        uses: actions/upload-artifact@main
        with:
          name: Dict-${{ matrix.version }}.json
          path: DictPacker/Dict-${{ matrix.version }}.json
          compression-level: 9

  release:
    needs: packer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Scripts
        uses: actions/checkout@main

      - uses: actions/setup-python@main
        with:
          python-version: "3.10"

      - name: Download JSON files
        uses: actions/download-artifact@main
        with:
          path: DictPacker
          merge-multiple: true

      - name: Pack Integral files
        run: python ./src/integral.py

      - name: Create timestamp
        id: create_timestamp
        run: echo "::set-output name=timestamp::$(date -u '+%Y_%m_%d_%H_%M_%S')"

      - name: Create release
        id: create_release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 模组词典-${{ steps.create_timestamp.outputs.timestamp }}
          release_name: 模组词典-${{ steps.create_timestamp.outputs.timestamp }}
          draft: false
          prerelease: false

      - name: Update release asset Integral
        uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # upload_url: ${{ steps.create_release.outputs.upload_url }}
          file: DictPacker/Dict.json
          update_latest_release: true

      - name: Update release asset Integral Minimal
        uses: xresloader/upload-to-github-release@main
        with:
          # upload_url: ${{ steps.create_release.outputs.upload_url }}
          file: DictPacker/Dict-Mini.json
          update_latest_release: true

      - name: Update release asset Integral Database
        uses: xresloader/upload-to-github-release@main
        with:
          # upload_url: ${{ steps.create_release.outputs.upload_url }}
          file: DictPacker/Dict-Sqlite.db
          update_latest_release: true
